//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKClient.Groups.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKClient.Groups.Localization.GroupResources", typeof(GroupResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на accept invitation.
        /// </summary>
        public static string AcceptInvitation {
            get {
                return ResourceManager.GetString("AcceptInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на audios.
        /// </summary>
        public static string Audios {
            get {
                return ResourceManager.GetString("Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cancel request.
        /// </summary>
        public static string CancelRequest {
            get {
                return ResourceManager.GetString("CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на closed community.
        /// </summary>
        public static string ClosedGroup {
            get {
                return ResourceManager.GetString("ClosedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decline invitation.
        /// </summary>
        public static string DeclineInvitation {
            get {
                return ResourceManager.GetString("DeclineInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decline.
        /// </summary>
        public static string EventDecline {
            get {
                return ResourceManager.GetString("EventDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на join.
        /// </summary>
        public static string EventJoin {
            get {
                return ResourceManager.GetString("EventJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на maybe.
        /// </summary>
        public static string EventMaybe {
            get {
                return ResourceManager.GetString("EventMaybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} communities.
        /// </summary>
        public static string FiveCommunitiesFrm {
            get {
                return ResourceManager.GetString("FiveCommunitiesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} events.
        /// </summary>
        public static string FiveEventsFrm {
            get {
                return ResourceManager.GetString("FiveEventsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} members.
        /// </summary>
        public static string FiveMembersFrm {
            get {
                return ResourceManager.GetString("FiveMembersFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} messages.
        /// </summary>
        public static string FiveMessagesFrm {
            get {
                return ResourceManager.GetString("FiveMessagesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} subscribers.
        /// </summary>
        public static string FiveSubscribersFrm {
            get {
                return ResourceManager.GetString("FiveSubscribersFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} topics.
        /// </summary>
        public static string FiveTopicsFrm {
            get {
                return ResourceManager.GetString("FiveTopicsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global search.
        /// </summary>
        public static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INVITATIONS.
        /// </summary>
        public static string GroupInvitationsPage_Title {
            get {
                return ResourceManager.GetString("GroupInvitationsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на information.
        /// </summary>
        public static string GroupPage_Info {
            get {
                return ResourceManager.GetString("GroupPage_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на page.
        /// </summary>
        public static string GroupPage_Page {
            get {
                return ResourceManager.GetString("GroupPage_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на all.
        /// </summary>
        public static string GroupsListPage_All {
            get {
                return ResourceManager.GetString("GroupsListPage_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на communities.
        /// </summary>
        public static string GroupsListPage_Communities {
            get {
                return ResourceManager.GetString("GroupsListPage_Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на events.
        /// </summary>
        public static string GroupsListPage_Events {
            get {
                return ResourceManager.GetString("GroupsListPage_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upcoming events.
        /// </summary>
        public static string GroupsListPage_FutureEvents {
            get {
                return ResourceManager.GetString("GroupsListPage_FutureEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на managed.
        /// </summary>
        public static string GroupsListPage_Manage {
            get {
                return ResourceManager.GetString("GroupsListPage_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Past events.
        /// </summary>
        public static string GroupsListPage_PastEvents {
            get {
                return ResourceManager.GetString("GroupsListPage_PastEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GROUPS.
        /// </summary>
        public static string GroupsListPage_Title {
            get {
                return ResourceManager.GetString("GroupsListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;S GROUPS.
        /// </summary>
        public static string GroupsListPage_TitleFrm {
            get {
                return ResourceManager.GetString("GroupsListPage_TitleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join .
        /// </summary>
        public static string JoinGroup {
            get {
                return ResourceManager.GetString("JoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на leave the group.
        /// </summary>
        public static string LeaveTheGroup {
            get {
                return ResourceManager.GetString("LeaveTheGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No communities yet.
        /// </summary>
        public static string NoCommunites {
            get {
                return ResourceManager.GetString("NoCommunites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No communities.
        /// </summary>
        public static string NoCommunitiesFound {
            get {
                return ResourceManager.GetString("NoCommunitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No events yet.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No invitations yet.
        /// </summary>
        public static string NoInvitations {
            get {
                return ResourceManager.GetString("NoInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No participants.
        /// </summary>
        public static string NoParticipantsYet {
            get {
                return ResourceManager.GetString("NoParticipantsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No subscribers.
        /// </summary>
        public static string NoSubscribersYet {
            get {
                return ResourceManager.GetString("NoSubscribersYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No topics yet.
        /// </summary>
        public static string NoTopics {
            get {
                return ResourceManager.GetString("NoTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} community.
        /// </summary>
        public static string OneCommunityFrm {
            get {
                return ResourceManager.GetString("OneCommunityFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} event.
        /// </summary>
        public static string OneEventFrm {
            get {
                return ResourceManager.GetString("OneEventFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} member.
        /// </summary>
        public static string OneMemberFrm {
            get {
                return ResourceManager.GetString("OneMemberFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} message.
        /// </summary>
        public static string OneMessageFrm {
            get {
                return ResourceManager.GetString("OneMessageFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} subscriber.
        /// </summary>
        public static string OneSubscriberFrm {
            get {
                return ResourceManager.GetString("OneSubscriberFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} topic.
        /// </summary>
        public static string OneTopicFrm {
            get {
                return ResourceManager.GetString("OneTopicFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PARTICIPANTS.
        /// </summary>
        public static string PARTICIPANTS {
            get {
                return ResourceManager.GetString("PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на private community.
        /// </summary>
        public static string PrivateGroup {
            get {
                return ResourceManager.GetString("PrivateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на open community.
        /// </summary>
        public static string PublicGroup {
            get {
                return ResourceManager.GetString("PublicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на public page.
        /// </summary>
        public static string PublicPage {
            get {
                return ResourceManager.GetString("PublicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT A COMMUNITY.
        /// </summary>
        public static string SELECTAGROUP {
            get {
                return ResourceManager.GetString("SELECTAGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на send request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на show on map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SUBSCRIBERS.
        /// </summary>
        public static string SUBSCRIBERS {
            get {
                return ResourceManager.GetString("SUBSCRIBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на topics.
        /// </summary>
        public static string themes {
            get {
                return ResourceManager.GetString("themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} communities.
        /// </summary>
        public static string TwoFourCommunitiesFrm {
            get {
                return ResourceManager.GetString("TwoFourCommunitiesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} events.
        /// </summary>
        public static string TwoFourEventsFrm {
            get {
                return ResourceManager.GetString("TwoFourEventsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} members.
        /// </summary>
        public static string TwoFourMembersFrm {
            get {
                return ResourceManager.GetString("TwoFourMembersFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} messages.
        /// </summary>
        public static string TwoFourMessagesFrm {
            get {
                return ResourceManager.GetString("TwoFourMessagesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} subscribers.
        /// </summary>
        public static string TwoFourSubscribersFrm {
            get {
                return ResourceManager.GetString("TwoFourSubscribersFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} topics.
        /// </summary>
        public static string TwoFourTopicsFrm {
            get {
                return ResourceManager.GetString("TwoFourTopicsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unsubscribe.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
