//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKClient.Audio.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AudioResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AudioResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKClient.Audio.Localization.AudioResources", typeof(AudioResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add to album.
        /// </summary>
        public static string AddToAlbum {
            get {
                return ResourceManager.GetString("AddToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ALBUM.
        /// </summary>
        public static string ALBUM {
            get {
                return ResourceManager.GetString("ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT ALBUM.
        /// </summary>
        public static string Albums_Chose {
            get {
                return ResourceManager.GetString("Albums_Chose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enter new album name.
        /// </summary>
        public static string Albums_Edit_Body {
            get {
                return ResourceManager.GetString("Albums_Edit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit album.
        /// </summary>
        public static string Albums_Edit_Caption {
            get {
                return ResourceManager.GetString("Albums_Edit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на album name.
        /// </summary>
        public static string Albums_New_Caption {
            get {
                return ResourceManager.GetString("Albums_New_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add album.
        /// </summary>
        public static string Albums_New_Title {
            get {
                return ResourceManager.GetString("Albums_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на new album name.
        /// </summary>
        public static string Albums_New_Watermark {
            get {
                return ResourceManager.GetString("Albums_New_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string AppBar_Add {
            get {
                return ResourceManager.GetString("AppBar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на playing now.
        /// </summary>
        public static string AppBar_NowPlaying {
            get {
                return ResourceManager.GetString("AppBar_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на search.
        /// </summary>
        public static string AppBar_Search {
            get {
                return ResourceManager.GetString("AppBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AUDIO.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT AUDIO.
        /// </summary>
        public static string AUDIO_CHOOSE {
            get {
                return ResourceManager.GetString("AUDIO_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create  album.
        /// </summary>
        public static string CreateAlbum {
            get {
                return ResourceManager.GetString("CreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete album.
        /// </summary>
        public static string DeleteAlbum {
            get {
                return ResourceManager.GetString("DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} audios.
        /// </summary>
        public static string DeleteFiveAudiosFrm {
            get {
                return ResourceManager.GetString("DeleteFiveAudiosFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} audio.
        /// </summary>
        public static string DeleteOneAudioFrm {
            get {
                return ResourceManager.GetString("DeleteOneAudioFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} audios.
        /// </summary>
        public static string DeleteTwoFourAudiosFrm {
            get {
                return ResourceManager.GetString("DeleteTwoFourAudiosFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit album.
        /// </summary>
        public static string EditAlbum {
            get {
                return ResourceManager.GetString("EditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string FiveAlbumsFrm {
            get {
                return ResourceManager.GetString("FiveAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} audios are added to album {1}. Go to album?.
        /// </summary>
        public static string FiveAudiosMovedFrm {
            get {
                return ResourceManager.GetString("FiveAudiosMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tracks.
        /// </summary>
        public static string FiveTracksFrm {
            get {
                return ResourceManager.GetString("FiveTracksFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete album.
        /// </summary>
        public static string Header_DeleteAlbum {
            get {
                return ResourceManager.GetString("Header_DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на albums.
        /// </summary>
        public static string MainPivot_Albums {
            get {
                return ResourceManager.GetString("MainPivot_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на all.
        /// </summary>
        public static string MainPivot_All {
            get {
                return ResourceManager.GetString("MainPivot_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding audio to album.
        /// </summary>
        public static string MoveAudios {
            get {
                return ResourceManager.GetString("MoveAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No albums yet.
        /// </summary>
        public static string NoAlbums {
            get {
                return ResourceManager.GetString("NoAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No tracks yet.
        /// </summary>
        public static string NoTracks {
            get {
                return ResourceManager.GetString("NoTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} album.
        /// </summary>
        public static string OneAlbumFrm {
            get {
                return ResourceManager.GetString("OneAlbumFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} audio is added to album {1}. Go to album?.
        /// </summary>
        public static string OneAudioMovedFrm {
            get {
                return ResourceManager.GetString("OneAudioMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} track.
        /// </summary>
        public static string OneTrackFrm {
            get {
                return ResourceManager.GetString("OneTrackFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на are you sure you want to delete {0} album ?.
        /// </summary>
        public static string Question_DeleteAlbum {
            get {
                return ResourceManager.GetString("Question_DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на search through all tracks.
        /// </summary>
        public static string Search_Info {
            get {
                return ResourceManager.GetString("Search_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string Track_Add {
            get {
                return ResourceManager.GetString("Track_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add to album.
        /// </summary>
        public static string Track_AddToAlbum {
            get {
                return ResourceManager.GetString("Track_AddToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на move to album.
        /// </summary>
        public static string Track_MoveToAlbum {
            get {
                return ResourceManager.GetString("Track_MoveToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string TwoFourAlbumsFrm {
            get {
                return ResourceManager.GetString("TwoFourAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} audios are added to album {1}. Go to album?.
        /// </summary>
        public static string TwoFourAudiosMovedFrm {
            get {
                return ResourceManager.GetString("TwoFourAudiosMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} tracks.
        /// </summary>
        public static string TwoFourTracksFrm {
            get {
                return ResourceManager.GetString("TwoFourTracksFrm", resourceCulture);
            }
        }
    }
}
