//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKClient.Video.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VideoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKClient.Video.Localization.VideoResources", typeof(VideoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на create album.
        /// </summary>
        public static string Album_Add {
            get {
                return ResourceManager.GetString("Album_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit album.
        /// </summary>
        public static string Album_Edit {
            get {
                return ResourceManager.GetString("Album_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на choose album.
        /// </summary>
        public static string Albums_Chose {
            get {
                return ResourceManager.GetString("Albums_Chose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string AppBar_Add {
            get {
                return ResourceManager.GetString("AppBar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на search.
        /// </summary>
        public static string AppBar_Search {
            get {
                return ResourceManager.GetString("AppBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author:.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are not allowed to delete this video..
        /// </summary>
        public static string CannotDeleteVideo {
            get {
                return ResourceManager.GetString("CannotDeleteVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete video.
        /// </summary>
        public static string DeleteVideo {
            get {
                return ResourceManager.GetString("DeleteVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while deleting video, please try again..
        /// </summary>
        public static string ErrorDeleteVideo {
            get {
                return ResourceManager.GetString("ErrorDeleteVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while moving video to album, please try again..
        /// </summary>
        public static string ErrorMovingVideo {
            get {
                return ResourceManager.GetString("ErrorMovingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error occured while saving album, please try again..
        /// </summary>
        public static string ErrorSavingAlbum {
            get {
                return ResourceManager.GetString("ErrorSavingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string FiveAlbumsFrm {
            get {
                return ResourceManager.GetString("FiveAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} videos.
        /// </summary>
        public static string FiveVideosFrm {
            get {
                return ResourceManager.GetString("FiveVideosFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} views.
        /// </summary>
        public static string FiveViewsFrm {
            get {
                return ResourceManager.GetString("FiveViewsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на albums.
        /// </summary>
        public static string MainPivot_Albums {
            get {
                return ResourceManager.GetString("MainPivot_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на all.
        /// </summary>
        public static string MainPivot_All {
            get {
                return ResourceManager.GetString("MainPivot_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на move to album.
        /// </summary>
        public static string MoveToAlbum {
            get {
                return ResourceManager.GetString("MoveToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No albums.
        /// </summary>
        public static string NoAlbums {
            get {
                return ResourceManager.GetString("NoAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No videos yet.
        /// </summary>
        public static string NoVideos {
            get {
                return ResourceManager.GetString("NoVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No views yet.
        /// </summary>
        public static string NoViews {
            get {
                return ResourceManager.GetString("NoViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} album.
        /// </summary>
        public static string OneAlbumFrm {
            get {
                return ResourceManager.GetString("OneAlbumFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} video.
        /// </summary>
        public static string OneVideoFrm {
            get {
                return ResourceManager.GetString("OneVideoFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} view.
        /// </summary>
        public static string OneViewFrm {
            get {
                return ResourceManager.GetString("OneViewFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In this video:.
        /// </summary>
        public static string OnThisVideo {
            get {
                return ResourceManager.GetString("OnThisVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на question.
        /// </summary>
        public static string Question_Caption {
            get {
                return ResourceManager.GetString("Question_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete {0} ?.
        /// </summary>
        public static string Question_Delete {
            get {
                return ResourceManager.GetString("Question_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string TwoFourAlbumsFrm {
            get {
                return ResourceManager.GetString("TwoFourAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} videos.
        /// </summary>
        public static string TwoFourVideosFrm {
            get {
                return ResourceManager.GetString("TwoFourVideosFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} views.
        /// </summary>
        public static string TwoFourViewsFrm {
            get {
                return ResourceManager.GetString("TwoFourViewsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string UC_AlbumTitle {
            get {
                return ResourceManager.GetString("UC_AlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} album.
        /// </summary>
        public static string UC_Title {
            get {
                return ResourceManager.GetString("UC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIDEO.
        /// </summary>
        public static string Video_Title {
            get {
                return ResourceManager.GetString("Video_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add to my videos.
        /// </summary>
        public static string VideoComments_AppBar_AddToVideos {
            get {
                return ResourceManager.GetString("VideoComments_AppBar_AddToVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We&apos;re sorry, this video is not available..
        /// </summary>
        public static string VideoNotAvailable {
            get {
                return ResourceManager.GetString("VideoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIDEOS.
        /// </summary>
        public static string VIDEOS {
            get {
                return ResourceManager.GetString("VIDEOS", resourceCulture);
            }
        }
    }
}
