//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKClient.Photos.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhotoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhotoResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKClient.Photos.Localization.PhotoResources", typeof(PhotoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photos.
        /// </summary>
        public static string AlbumsPhotosCountFiveFrm {
            get {
                return ResourceManager.GetString("AlbumsPhotosCountFiveFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photo.
        /// </summary>
        public static string AlbumsPhotosCountOneFrm {
            get {
                return ResourceManager.GetString("AlbumsPhotosCountOneFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photos.
        /// </summary>
        public static string AlbumsPhotosCountTwoFrm {
            get {
                return ResourceManager.GetString("AlbumsPhotosCountTwoFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Who can view the album?.
        /// </summary>
        public static string CreateAlbumUC_Access {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на all users.
        /// </summary>
        public static string CreateAlbumUC_Access_AllUsers {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на friends of friends.
        /// </summary>
        public static string CreateAlbumUC_Access_FriendsOfFriends {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access_FriendsOfFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на friends only.
        /// </summary>
        public static string CreateAlbumUC_Access_FriendsOnly {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access_FriendsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на group members.
        /// </summary>
        public static string CreateAlbumUC_Access_GroupMembers {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access_GroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на only me.
        /// </summary>
        public static string CreateAlbumUC_Access_OnlyMe {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Access_OnlyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Who can comment?.
        /// </summary>
        public static string CreateAlbumUC_Comments {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на create.
        /// </summary>
        public static string CreateAlbumUC_Create {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create album.
        /// </summary>
        public static string CreateAlbumUC_CreateAlbum {
            get {
                return ResourceManager.GetString("CreateAlbumUC_CreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string CreateAlbumUC_Description {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit album.
        /// </summary>
        public static string CreateAlbumUC_EditAlbum {
            get {
                return ResourceManager.GetString("CreateAlbumUC_EditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hm, couldn&apos;t save the album..
        /// </summary>
        public static string CreateAlbumUC_Error {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string CreateAlbumUC_Save {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string CreateAlbumUC_Title {
            get {
                return ResourceManager.GetString("CreateAlbumUC_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} albums.
        /// </summary>
        public static string DeleteAlbumsFrm {
            get {
                return ResourceManager.GetString("DeleteAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} album.
        /// </summary>
        public static string DeleteOneAlbumFrm {
            get {
                return ResourceManager.GetString("DeleteOneAlbumFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} photo.
        /// </summary>
        public static string DeleteOnePhoto {
            get {
                return ResourceManager.GetString("DeleteOnePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This action cannot be undone, do you want to proceed?.
        /// </summary>
        public static string DeletePhotoConfirmation {
            get {
                return ResourceManager.GetString("DeletePhotoConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0} photos.
        /// </summary>
        public static string DeletePhotosFrm {
            get {
                return ResourceManager.GetString("DeletePhotosFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cancel.
        /// </summary>
        public static string EditAlbumPage_AppBar_Cancel {
            get {
                return ResourceManager.GetString("EditAlbumPage_AppBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string EditAlbumPage_AppBar_Delete {
            get {
                return ResourceManager.GetString("EditAlbumPage_AppBar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на move to album.
        /// </summary>
        public static string EditAlbumPage_AppBar_MoveToAlbum {
            get {
                return ResourceManager.GetString("EditAlbumPage_AppBar_MoveToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string FiveAlbumsFrm {
            get {
                return ResourceManager.GetString("FiveAlbumsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This action cannot be undone, do you want to proceed?.
        /// </summary>
        public static string GenericConfirmation {
            get {
                return ResourceManager.GetString("GenericConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на comment.
        /// </summary>
        public static string ImageViewer_AppBar_Comment {
            get {
                return ResourceManager.GetString("ImageViewer_AppBar_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на save.
        /// </summary>
        public static string ImageViewer_AppBar_Save {
            get {
                return ResourceManager.GetString("ImageViewer_AppBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} of {1}.
        /// </summary>
        public static string ImageViewer_PhotoCounterFrm {
            get {
                return ResourceManager.GetString("ImageViewer_PhotoCounterFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready!.
        /// </summary>
        public static string ImageViewer_Ready {
            get {
                return ResourceManager.GetString("ImageViewer_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No albums yet.
        /// </summary>
        public static string NoAlbums {
            get {
                return ResourceManager.GetString("NoAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} album.
        /// </summary>
        public static string OneAlbumFrm {
            get {
                return ResourceManager.GetString("OneAlbumFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add photo.
        /// </summary>
        public static string PhotoAlbumPage_AddPhoto {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit.
        /// </summary>
        public static string PhotoAlbumPage_AppBar_Edit {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_AppBar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string PhotoAlbumPage_Delete {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на choose album cover.
        /// </summary>
        public static string PhotoAlbumPage_MakeCover {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_MakeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No photos in this album yet..
        /// </summary>
        public static string PhotoAlbumPage_NoPhotos {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_NoPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move photos to album.
        /// </summary>
        public static string PhotoAlbumPage_PhotoMove {
            get {
                return ResourceManager.GetString("PhotoAlbumPage_PhotoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photos were moved to album &quot;{1}&quot;. Do you want to go to the album?.
        /// </summary>
        public static string PhotoAlbumPageFivePhotosMovedFrm {
            get {
                return ResourceManager.GetString("PhotoAlbumPageFivePhotosMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photo was moved to album &quot;{1}&quot;. Do you want to go to the album?.
        /// </summary>
        public static string PhotoAlbumPageOnePhotoMovedFrm {
            get {
                return ResourceManager.GetString("PhotoAlbumPageOnePhotoMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} photos were moved to album &quot;{1}&quot;. Do you want to go to the album?.
        /// </summary>
        public static string PhotoAlbumPageTwoFourPhotosMovedFrm {
            get {
                return ResourceManager.GetString("PhotoAlbumPageTwoFourPhotosMovedFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author: .
        /// </summary>
        public static string PhotoCommentsPage_Author {
            get {
                return ResourceManager.GetString("PhotoCommentsPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PHOTO.
        /// </summary>
        public static string PhotoCommentsPage_PHOTO {
            get {
                return ResourceManager.GetString("PhotoCommentsPage_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The photo is saved..
        /// </summary>
        public static string PhotoIsSaved {
            get {
                return ResourceManager.GetString("PhotoIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на albums.
        /// </summary>
        public static string PhotosMainPage_Albums {
            get {
                return ResourceManager.GetString("PhotosMainPage_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string PhotosMainPage_Albums_Add {
            get {
                return ResourceManager.GetString("PhotosMainPage_Albums_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на edit.
        /// </summary>
        public static string PhotosMainPage_Albums_Edit {
            get {
                return ResourceManager.GetString("PhotosMainPage_Albums_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete.
        /// </summary>
        public static string PhotosMainPage_Albums_Remove {
            get {
                return ResourceManager.GetString("PhotosMainPage_Albums_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All photos.
        /// </summary>
        public static string PhotosMainPage_AllPhotos {
            get {
                return ResourceManager.GetString("PhotosMainPage_AllPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHOOSE AN ALBUM.
        /// </summary>
        public static string PhotosMainPage_ChooseAlbum {
            get {
                return ResourceManager.GetString("PhotosMainPage_ChooseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на refresh.
        /// </summary>
        public static string PhotosMainPage_Feed_Refresh {
            get {
                return ResourceManager.GetString("PhotosMainPage_Feed_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PHOTOS.
        /// </summary>
        public static string PhotosMainPage_MyPhotosTitle {
            get {
                return ResourceManager.GetString("PhotosMainPage_MyPhotosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на feed.
        /// </summary>
        public static string PhotosMainPage_PhotosFeed {
            get {
                return ResourceManager.GetString("PhotosMainPage_PhotosFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;s PHOTOS.
        /// </summary>
        public static string PhotosMainPage_PhotosOfTitleFrm {
            get {
                return ResourceManager.GetString("PhotosMainPage_PhotosOfTitleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photos with {0}.
        /// </summary>
        public static string PhotosMainPage_PhotosWithFormat {
            get {
                return ResourceManager.GetString("PhotosMainPage_PhotosWithFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile photos.
        /// </summary>
        public static string PhotosMainPage_ProfilePhotos {
            get {
                return ResourceManager.GetString("PhotosMainPage_ProfilePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved photos.
        /// </summary>
        public static string PhotosMainPage_SavedPhotos {
            get {
                return ResourceManager.GetString("PhotosMainPage_SavedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}&apos;s PHOTOS.
        /// </summary>
        public static string PhotosMainPage_TitleFrm {
            get {
                return ResourceManager.GetString("PhotosMainPage_TitleFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wall photos.
        /// </summary>
        public static string PhotosMainPage_WallPhotos {
            get {
                return ResourceManager.GetString("PhotosMainPage_WallPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On this photo:.
        /// </summary>
        public static string PhotoUC_OnThisPhoto {
            get {
                return ResourceManager.GetString("PhotoUC_OnThisPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving image.
        /// </summary>
        public static string SavingImage {
            get {
                return ResourceManager.GetString("SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} albums.
        /// </summary>
        public static string TwoFourAlbumsFrm {
            get {
                return ResourceManager.GetString("TwoFourAlbumsFrm", resourceCulture);
            }
        }
    }
}
